spring.application.name=FideNoticias


spring.datasource.url=jdbc:oracle:thin:@localhost:15211:XE
spring.datasource.username=FIDENOTICIAS
spring.datasource.password=Fide2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML


app.noticias.max-resultados=10

server.port=8081